config/routes.rb
Rails.application.routes.draw do
  get    '/roles',   to: 'roles#index'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get    '/logout',  to: 'sessions#destroy'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#new'
  resources :users
  resources :venues
  resources :tours
  resources :games do
    get "clone"
  end
  root 'games#index'
end

app/models/tour.rb
class Tour < ApplicationRecord
  has_many :games
  has_and_belongs_to_many :user
  has_many :role_types, :as => :object
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy]

  # GET /tours
  # GET /tours.json
  def index
    @tours = Tour.all
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
    games = Game.where(tour: @tour).uniq {|x| x.venue}
    venues = games.map{ |s| s.venue }
    @map = venues.empty? ? " " : js_map_maker(venues)
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)

    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:name, :notes, :user_id)
    end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_form.html.erb
<%= form_with(model: tour, local: true) do |form| %>
  <% if tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
      <% tour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :tour_name %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes, id: :tour_notes %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :tour_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tours/edit.html.erb
<h1>Editing Tour</h1>

<%= render 'form', tour: @tour %>

<%= link_to 'Show', @tour %> |
<%= link_to 'Back', tours_path %>

app/views/tours/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tours</h1>

<table class="table-dark table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Notes</th>
      <th>User</th>
      <% if current_user %>
        <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @tours.each do |tour| %>
      <tr>
        <td><%= tour.name %></td>
        <td><%= tour.notes %></td>
        <td><%= tour.user.name %></td>
        <% if current_user %>
        <td><%= link_to 'Show', tour %></td>
        <td><%= link_to 'Edit', edit_tour_path(tour) %></td>
        <td><%= link_to 'Destroy', tour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tour', new_tour_path %>

app/views/tours/new.html.erb
<h1>New Tour</h1>

<%= render 'form', tour: @tour %>

<%= link_to 'Back', tours_path %>

app/views/tours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tour.name %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @tour.notes %>
</p>

<p>
  <strong>User:</strong>
  <%= @tour.user.name %>
</p>

<%= @map %>
<%= link_to 'Edit', edit_tour_path(@tour) %> |
<%= link_to 'Back', tours_path %>