config/routes.rb
Rails.application.routes.draw do
  get    '/roles',   to: 'roles#index'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get    '/logout',  to: 'sessions#destroy'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#new'
  resources :users
  resources :venues
  resources :tours
  resources :games do
    get "clone"
  end
  root 'games#index'
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :tour
  belongs_to :venue

  accepts_nested_attributes_for :tour, :venue


 def offset_of_next_game
   d = Date.parse(self.day)
   d += 7  if d < Date.today
   d - Date.today
 end

 def time_sort
   val = self.start_time.split(":")
   sum = val[0].to_i * 2
   temp = val[1].split(//)
   sum += 24 if (sum < 24 && temp[2] == "P")
   sum += 1 if temp[0] == "3"
   sum
 end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :get_data

  # GET /games
  # GET /games.json
  def index
    @map_temp = js_map_maker(Venue.all.to_a)
    @editable_tours = current_user ? current_user.tours : []
    active_games = Game.where(active: true)
    @games = active_games.sort_by {|game| [game.offset_of_next_game, game.time_sort] }
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  def clone
    @game = Game.find(params[:game_id]).dup
    @game.save!
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    return unless (current_user.tours.include? @game.tour)
    @game.active = false
    @game.save!
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])

    end

    def get_data
      @venues = Venue.all
      @tours = Tour.all
      create_start_times
      @days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:id, :name, :notes, :tour_id, :venue_id, :start_time, :day)
    end

    def create_start_times
      @start_times = Array.new
      ['8','9','10','11'].each { |i|
        @start_times << (i +':00AM')
        @start_times << (i +':30AM')
      }
      ['12','1','2','3','4','5','6','7','8','9','10'].each { |i|
        @start_times << (i +':00PM')
        @start_times << (i +':30PM')
      }
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_display.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @game.notes %>
</p>

<p>
  <strong>Tour:</strong>
  <%= @game.tour.name %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @game.venue.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @game.start_time %>
</p>

<p>
  <strong>Day:</strong>
  <%= @game.day %>
</p>

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :game_name %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes, id: :game_notes %>
  </div>

  <div class="field">
    <%= form.label :tour_id %>
    <%= collection_select(:game, :tour_id, @tours, :id, :name, {:prompt => true}) %>
  </div>

  <div class="field">
    <%= form.label :venue_id %>
    <%= collection_select(:game, :venue_id, @venues, :id, :name, {:prompt => true}) %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.select :start_time, @start_times%>
  </div>

  <div class="field">
    <%= form.label :day %>
    <%= form.select :day, @days %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/clone.html.erb
<h1>Successfully Cloned Game</h1>

<%= render 'display', game: @game %>
<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to "Clone", "/games/#{@game.id}/clone" %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= @notice %></p>

<br>
<%= @map_temp %>
<br/>

<h1>Games</h1>

<table class="table-dark table-striped">
  <thead>
    <tr>
    <th>Day</th>
    <th>Start time</th>
    <th>Venue</th>
    <th>Tour</th>
      <th>Name</th>
      <th>Notes</th>
      <% if current_user %>
        <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><h1><%= game.day %></h1></td>
        <td><%= game.start_time %></td>
        <td><%= current_user ? (link_to game.venue.name, game.venue) : game.venue.name %></td>
        <td><%= game.tour.name %></td>
        <td><%= game.name %></td>
        <td><%= game.notes %></td>
        <% if current_user && (@editable_tours.include? game.tour)%>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @game.notes %>
</p>

<p>
  <strong>Tour:</strong>
  <%= @game.tour.name %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @game.venue.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @game.start_time %>
</p>

<p>
  <strong>Day:</strong>
  <%= @game.day %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>