config/routes.rb
Rails.application.routes.draw do
  get    '/roles',   to: 'roles#index'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get    '/logout',  to: 'sessions#destroy'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#new'
  resources :users
  resources :venues
  resources :tours
  resources :games do
    get "clone"
  end
  root 'games#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Utah Poker Atlas</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  </head>

  <body>
    <div class="upa_background">


    <div class="upa_image_header center">
      <%= link_to image_tag("upa_header.jpg"), root_path, class: 'upa_image'  %>
    </div>
    <div id="upa_navbar">
      <nav class="navbar navbar-expand-sm bg-dark">

        <ul class="nav">
        <li><%= link_to 'Games', games_path, class: 'nav-link' %></li>
        <% if current_user %>
        <li class="nav-item"><%= link_to 'Venues', venues_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Tours', tours_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Log out', logout_path, class: 'nav-link' %></li>
        <% else %>
        <li class="nav-item"><%= link_to 'Log In', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul></nav>
    </div>

    <p> <%= current_user.name if current_user %>  </p>

    <%= yield %>
    <div class="">
      <em>&copy; 2018 Utah Poker Atlas</em>
    </div></div>
  </body>
</html>